services:
  - type: web
    name: rankforge-backend
    env: python
    region: ohio # Change this if you prefer another region
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && bash run.sh"
    envVars:
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: NVIDIA_BASE_URL
        value: "https://integrate.api.nvidia.com/v1"
      - key: NVIDIA_MODEL
        value: "meta/llama-3.1-70b-instruct"
      - key: SERPAPI_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://frontend-lake-five-56.vercel.app"
